### ISSUE TITLE
UI details need to be improved

### ISSUE THREAD

**Issue by tiandi111** [LeonChen66/TAMUber#1]
Here are some UI details need to be improved:

- [x] Leave margins on the up, left and right borders of aggie map

- [x] Shorten the margin between aggie map and "onduties" list

- [x] Delete the strip with the watermark "Powered by Esri" at the bottom of aggie map

**Note: If you decide to solve one or several issues listed above, please leave a comment to notify others so that people don't do repeated work. In your comment, please indicate which issues you are going to solve and report your progress often.** 

Thank you, enjoy coding! 💯

**Comment by dongdongh233** [comment]
task1 and 3 has been finished and the style is edited in application.scss

**Comment by tiandi111** [comment]
Thanks for @dongdongh233 , the issues have been successfully solved!
